<a href="https://colab.research.google.com/github/UKD1211/DataScience_Slogbook_ISI_placement_prep/blob/main/task_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


In [2]:
import numpy as np
x = np.random.randint(1,100,12).reshape(4,3)
x

array([[93, 89, 85],
       [67, 52, 13],
       [87, 31, 72],
       [34, 49, 84]])

See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [3]:
np.sort(x)

array([[85, 89, 93],
       [13, 52, 67],
       [31, 72, 87],
       [34, 49, 84]])

In [4]:
b = x.copy()
b[:,1] = np.sort(b[:,1])
b

array([[93, 31, 85],
       [67, 49, 13],
       [87, 52, 72],
       [34, 89, 84]])

In [5]:
b = x[x[:,1].argsort()]
b

array([[87, 31, 72],
       [34, 49, 84],
       [67, 52, 13],
       [93, 89, 85]])

In [6]:
np.sort(x,axis=1)

array([[85, 89, 93],
       [13, 52, 67],
       [31, 72, 87],
       [34, 49, 84]])

In [7]:
y = np.max(x,axis=1)
z = y.argsort()
sort_arr = x[z]
sort_arr

array([[67, 52, 13],
       [34, 49, 84],
       [87, 31, 72],
       [93, 89, 85]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [8]:
# code here

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [43]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

unique_rows = np.unique(arr, axis = 0)
print(unique_rows)

unique_cols = np.unique(arr, axis = 1)
print(unique_cols)



[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [34]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print(np.flip(b))        # Flips both axes
# [[6 5 4]
#  [3 2 1]]

print(np.flip(b, axis=0))  # Flip rows (up-down)
# [[4 5 6]
#  [1 2 3]]

print(np.flip(b, axis=1))  # Flip columns (left-right)
# [[3 2 1]
#  [6 5 4]]


[[6 5 4]
 [3 2 1]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [33]:
arr = np.array([[1,2,3,4,5],[10,-3,30,4,5],[3,2,5,-4,5],[9,7,3,6,5]])
np.unique(np.where(arr>6)[0])

array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [12]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [25]:
import numpy as np
np.concatenate((arr1,arr2,arr3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [14]:
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr


array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [15]:
l = np.sort(arr)
l[:,1:-1]

array([[117, 123, 136, 137, 171, 173, 178, 181, 191, 193, 194, 197, 207,
        209, 211, 215, 218, 222, 225, 226, 227, 228, 228, 230, 231, 235,
        236, 240, 244, 246, 251, 262, 263, 265, 266, 267, 270, 277, 278,
        291, 291, 295, 296, 298, 307, 308, 318, 320, 323, 324, 325, 328,
        336, 340, 345, 353, 356, 362, 372, 373, 385, 387, 395, 418, 420,
        425, 426, 433, 436, 448, 449, 453, 458, 458, 459, 460, 464, 469,
        470, 472, 482, 483, 490, 490, 496, 503, 506, 507, 510, 513, 514,
        514, 525, 527, 527, 528, 534, 554, 557, 559, 563, 566, 569, 575,
        587, 588, 592, 607, 613, 617, 618, 620, 621, 624, 627, 628, 635,
        635, 637, 639, 645, 649, 654, 658, 677, 687, 695, 699, 702, 705,
        710, 711, 719, 724, 728, 729, 739, 743, 743, 748, 757, 761, 763,
        771, 774, 781, 782, 786, 790, 800, 803, 804, 818, 824, 825, 830,
        840, 853, 855, 859, 872, 875, 879, 882, 883, 885, 889, 892, 895,
        900, 908, 914, 917, 920, 920, 921, 922, 922

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [16]:
import numpy as np

a = np.random.randint(100,700,20)

def limit(arr: np.ndarray):
    # Step 1: Limit values between 100 and 200
    clipped = np.clip(arr, 100, 200)

    # Step 2: Sort the array
    sorted_arr = np.sort(clipped)

    # Step 3: Cumulative sum
    cumsum_arr = np.cumsum(sorted_arr)

    return cumsum_arr

print("Original array:", a)
print("Result:", limit(a))


Original array: [505 381 689 427 478 573 483 394 401 223 644 249 392 454 524 282 632 300
 646 249]
Result: [ 200  400  600  800 1000 1200 1400 1600 1800 2000 2200 2400 2600 2800
 3000 3200 3400 3600 3800 4000]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [17]:
import numpy as np
x = np.linspace(0,1,20)
x= np.round(x,3)
x

array([0.   , 0.053, 0.105, 0.158, 0.211, 0.263, 0.316, 0.368, 0.421,
       0.474, 0.526, 0.579, 0.632, 0.684, 0.737, 0.789, 0.842, 0.895,
       0.947, 1.   ])

In [18]:
np.min(x)

np.float64(0.0)

In [19]:
np.max(x)

np.float64(1.0)

In [20]:
np.median(x)

np.float64(0.5)

In [21]:
# 51th percentile
z = (51/100)*(len(x)+1)
print(np.floor(z))

10.0


In [22]:
x[[9,10]]

array([0.474, 0.526])

In [23]:
np.percentile(x,50)

np.float64(0.5)

In [24]:
np.percentile(x,51) - np.percentile(x,50)

np.float64(0.00988)